
services:
  # Sitemap generator (init container)
  utazon-sitemap-staging:
    image: ${DOCKER_USERNAME}/${APP_NAME}:${IMAGE_VERSION}
    container_name: ${APP_NAME}-sitemap-staging
    command: ["npm", "run", "sitemap:docker"]
    environment:
      - VITE_SITE_URL=https://${UTAZON_DOMAIN_STAGING}
    volumes:
      - sitemap_staging:/app
    networks:
      - traefik_public
    restart: "no"  # Run once and exit
    profiles:
      - init  # Use profile to control when this runs

  # Robots.txt generator (init container)
  utazon-robots-staging:
    image: ${DOCKER_USERNAME}/${APP_NAME}:${IMAGE_VERSION}
    container_name: ${APP_NAME}-robots-staging
    command: ["npm", "run", "robots:docker"]
    environment:
      - VITE_SITE_URL=https://${UTAZON_DOMAIN_STAGING}
    volumes:
      - sitemap_staging:/app
    networks:
      - traefik_public
    restart: "no"  # Run once and exit
    profiles:
      - init  # Use profile to control when this runs

  # Main application
  utazon-staging:
    image: ${DOCKER_USERNAME}/${APP_NAME}:${IMAGE_VERSION}
    container_name: ${APP_NAME}-staging
    volumes:
      - sitemap_staging:/usr/share/nginx/html/seo:ro
    expose:
      - 80
    networks:
      - traefik_public
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${APP_NAME}-staging.rule=Host(`${UTAZON_DOMAIN_STAGING}`)"
      - "traefik.http.routers.${APP_NAME}-staging.tls=true"
      - "traefik.http.routers.${APP_NAME}-staging.entrypoints=web,websecure"
      - "traefik.http.routers.${APP_NAME}-staging.tls.certresolver=letsencrypt"
      - "traefik.http.services.${APP_NAME}-staging.loadbalancer.server.port=80"
      - "traefik.http.middlewares.${APP_NAME}-auth.basicauth.users=${UTAZON_SIMPLE_AUTH_HASH}"
      - "traefik.http.routers.${APP_NAME}-staging.middlewares=${APP_NAME}-auth"

volumes:
  sitemap_staging:

networks:
  traefik_public:
    external: true
