services:
  utazon:
    image: ${DOCKER_USERNAME}/${APP_NAME}:${IMAGE_VERSION}
    container_name: ${APP_NAME}-staging
    expose:
      - 80
    networks:
      - traefik_public
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${APP_NAME}-staging.rule=Host(`${UTAZON_DOMAIN_STAGING}`)"
      - "traefik.http.routers.${APP_NAME}-staging.tls=true"
      - "traefik.http.routers.${APP_NAME}-staging.entrypoints=web,websecure"
      - "traefik.http.routers.${APP_NAME}-staging.tls.certresolver=letsencrypt"
      - "traefik.http.services.${APP_NAME}-staging.loadbalancer.server.port=80"
      - "traefik.http.middlewares.${APP_NAME}-auth.basicauth.users=${UTAZON_SIMPLE_AUTH_HASH}"
      - "traefik.http.routers.${APP_NAME}-staging.middlewares=${APP_NAME}-auth"

networks:
  traefik_public:
    external: true
