
services:
  # Sitemap generator (init container)
  utazon-sitemap-production:
    image: ${DOCKER_USERNAME}/${APP_NAME}:${IMAGE_VERSION}
    container_name: ${APP_NAME}-sitemap-production
    command: ["npm", "run", "sitemap:docker"]
    environment:
      - VITE_SITE_URL=https://${UTAZON_DOMAIN_PRODUCTION}
    volumes:
      - sitemap_production:/app
    networks:
      - traefik_public
    restart: "no"  # Run once and exit
    profiles:
      - init  # Use profile to control when this runs

  # Robots.txt generator (init container)
  utazon-robots-production:
    image: ${DOCKER_USERNAME}/${APP_NAME}:${IMAGE_VERSION}
    container_name: ${APP_NAME}-robots-production
    command: ["npm", "run", "robots:docker"]
    environment:
      - VITE_SITE_URL=https://${UTAZON_DOMAIN_PRODUCTION}
    volumes:
      - sitemap_production:/app
    networks:
      - traefik_public
    restart: "no"  # Run once and exit
    profiles:
      - init  # Use profile to control when this runs

  # Main application
  utazon-production:
    image: ${DOCKER_USERNAME}/${APP_NAME}:${IMAGE_VERSION}
    container_name: ${APP_NAME}-production
    volumes:
      - sitemap_production:/usr/share/nginx/html:ro
    expose:
      - 80
    networks:
      - traefik_public
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${APP_NAME}-production.rule=Host(`${UTAZON_DOMAIN_PRODUCTION}`)"
      - "traefik.http.routers.${APP_NAME}-production.tls=true"
      - "traefik.http.routers.${APP_NAME}-production.entrypoints=web,websecure"
      - "traefik.http.routers.${APP_NAME}-production.tls.certresolver=letsencrypt"
      - "traefik.http.services.${APP_NAME}-production.loadbalancer.server.port=80"

volumes:
  sitemap_production:

networks:
  traefik_public:
    external: true
