services:
  utazon:
    image: ${DOCKER_USERNAME}/${APP_NAME}:${IMAGE_VERSION}
    container_name: ${APP_NAME}-production
    expose:
      - 80
    networks:
      - traefik_public
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${APP_NAME}-prod.rule=Host(`${UTAZON_DOMAIN_PROD}`)"
      - "traefik.http.routers.${APP_NAME}-prod.tls=true"
      - "traefik.http.routers.${APP_NAME}-prod.entrypoints=web,websecure"
      - "traefik.http.routers.${APP_NAME}-prod.tls.certresolver=letsencrypt"
      - "traefik.http.services.${APP_NAME}-prod.loadbalancer.server.port=80"

networks:
  traefik_public:
    external: true
